In [1]:
%reload_ext autoreload
%autoreload 2

In [2]:
import qiskit_metal as metal
from qiskit_metal import designs, draw
from qiskit_metal import MetalGUI, Dict, Headings
from qiskit_metal.qlibrary.qubits.transmon_cross import TransmonCross
from qiskit_metal.qlibrary.resonator.readoutres_fc import ReadoutResFC
import math
import numpy as np

# suppress deprecation warnings
import warnings
warnings.filterwarnings("ignore", category=Warning)

In [3]:
# Initialise design
design = designs.DesignFlipChip()
# Specify design name
design.metadata['design_name'] = 'FlipChip_Device'
# launch GUI
gui = MetalGUI(design)
# Allow running the same cell here multiple times to overwrite changes
design.overwrite_enabled = True

In [4]:
# delete existing components
design.delete_all_components()

# draw an Xmon on the Q_chip. Notice that I have defined one more item called chip and set it to be the 'Q_chip'
options_cpads = Dict(
        connector_type = '0', # claw type
        claw_length = '30um',
        ground_spacing = '5um',
        claw_width = '10um',
        claw_gap = '6um')
options = Dict(
    chip = 'Q_chip',
    cross_width = '20um',
    cross_length = '150um',
    cross_gap = '20um',
    connection_pads = Dict(
        claw_west = Dict(connector_location= '180', **options_cpads)))

# position the center of the Xmon at (0,0)
q1_x = '0.0 mm'
q1_y = '0.0 mm'

# build the device, positioned at (q1_x, q1_y)
q1 = TransmonCross(design, 'Q1', options = Dict(pos_x=q1_x, pos_y=q1_y, **options))

# rebuild in gui
gui.rebuild()
gui.autoscale()

In [5]:
# delete existing components
design.delete_all_components()

# draw an Xmon on the Q_chip. Notice that I have defined one more item called chip and set it to be the 'Q_chip'
options_cpads = Dict(
        connector_type = '0', # claw type
        claw_length = '30um',
        ground_spacing = '5um',
        claw_width = '10um',
        claw_gap = '6um')
options = Dict(
    chip = 'Q_chip',
    cross_width = '20um',
    cross_length = '150um',
    cross_gap = '20um',
    connection_pads = Dict(
        claw_west = Dict(connector_location= '180', **options_cpads)))

# position the center of the Xmon at (0,0)
q1_x = '0.0 mm'
q1_y = '0.0 mm'

# build the device, positioned at (q1_x, q1_y)
q1 = TransmonCross(design, 'Q1', options = Dict(pos_x=q1_x, pos_y=q1_y, **options))

# rebuild in gui
gui.rebuild()
gui.autoscale()

In [6]:
# draw a readout resonator on the C_chip. Note that we specify the chip='C_chip'.
# The readout resonator can me made into any shape. Here I opted to use a lambda/4 cpw-based resonator.
# The open-ended end of the resonator has a circular shape with a radius of readout_radius. Change this radius to change the qubit-resonator coupling strength.
# The cpw_width and cpw_gap are the size of the signal line and the ground gap of the cpw transmission line.
# The parameters readout_l1 ... l5, are the lengths of various parts of the cpw.
# arc_step is the length of a line that approximates an arc.
options = Dict(
    chip = 'C_chip',
    readout_radius = '20 um',
    readout_cpw_width = '10 um',
    readout_cpw_gap = '10 um',
    readout_cpw_turnradius = '50 um',
    readout_l1 = '600 um',
    readout_l2 = '200 um',
    readout_l3 = '300 um',
    readout_l4 = '150 um',
    readout_l5 = '550 um',
    arc_step = '5 um')

# the resonator is set to have its origin at the center of the circular patch.
# So we set the qubit and the resonator to share the same coordinate (q1_x, q1_y)
r1 = ReadoutResFC(design, 'R1', options = Dict(pos_x = q1_x, pos_y = q1_y, **options))

# rebuild in gui
gui.rebuild()
gui.autoscale()

In [7]:
a_gds = design.renderers.gds
a_gds.options.negative_mask = {'Q_chip': []}
a_gds.options.cheese.view_in_file =  {'Q_chip': {1: True}, 'C_chip':{1:True}}
a_gds.options.no_cheese.view_in_file =  {'Q_chip': {1: True}, 'C_chip':{1:True}}
a_gds.options

{'short_segments_to_not_fillet': 'True',
 'check_short_segments_by_scaling_fillet': '2.0',
 'gds_unit': 0.001,
 'ground_plane': 'True',
 'negative_mask': {'Q_chip': []},
 'fabricate': 'False',
 'corners': 'circular bend',
 'tolerance': '0.00001',
 'precision': '0.000000001',
 'width_LineString': '10um',
 'path_filename': '../resources/Fake_Junctions.GDS',
 'junction_pad_overlap': '5um',
 'max_points': '199',
 'cheese': {'datatype': '100',
  'shape': '0',
  'cheese_0_x': '25um',
  'cheese_0_y': '25um',
  'cheese_1_radius': '100um',
  'view_in_file': {'Q_chip': {1: True}},
  'delta_x': '100um',
  'delta_y': '100um',
  'edge_nocheese': '200um'},
 'no_cheese': {'datatype': '99',
  'buffer': '25um',
  'cap_style': '2',
  'join_style': '2',
  'view_in_file': {'Q_chip': {1: True}}},
 'bounding_box_scale_x': '1.2',
 'bounding_box_scale_y': '1.2'}

In [8]:
a_gds.export_to_gds('flip_chip_test.gds')

11:48AM 04s WARNING [_import_junctions_to_one_cell]: Not able to find file:"../resources/Fake_Junctions.GDS".  Not used to replace junction. Checked directory:"C:\Users\CJZ\PycharmProjects\resources".
11:48AM 04s WARNING [_import_junctions_to_one_cell]: Not able to find file:"../resources/Fake_Junctions.GDS".  Not used to replace junction. Checked directory:"C:\Users\CJZ\PycharmProjects\resources".
11:48AM 04s WARNING [_check_either_cheese]: Chip=C_chip is not either in no_cheese_view_in_file or cheese_view_in_file from self.options.
11:48AM 04s WARNING [_check_either_cheese]: Chip=C_chip is not either in no_cheese_view_in_file or cheese_view_in_file from self.options.


1

In [18]:
x = np.array([1,2])
y = np.array([2,2])
z = np.array([2,3])
h = np.array([3,7])
xs,ys = x+y
xs,ys

np.array([x,y,z,h]).shape

(4, 2)

In [9]:
def  vector_rotation(vec,angle):
    theta = np.deg2rad(angle)
    rot = np.array([[math.cos(theta), -math.sin(theta)], [math.sin(theta), math.cos(theta)]])
    return np.dot(rot,vec)

v = np.array([1, 0])
vector_rotation(v,90)

array([6.123234e-17, 1.000000e+00])

In [2]:
for i in [2,3,1,4]:
    print(i)

2
3
1
4


In [1]:
int(4.5)

4

In [8]:
x,y =[1,2]* np.array([2,3])
# x0 = x+3
# np.concatenate([x,x0])
x,y

TypeError: can't multiply sequence by non-int of type 'list'

In [6]:
flip_resonator_list = np.array([0,19,20,21,22])
# for i in range(3):
#     flip_resonator_list = np.concatenate([flip_resonator_list,flip_resonator_list+23])
flip_resonator_list=np.append(flip_resonator_list,1)
flip_resonator_list

array([ 0, 19, 20, 21, 22,  1])

In [9]:
for i in flip_resonator_list:
    print(i)

0
19
20
21
22
23
42
43
44
45
23
42
43
44
45
46
65
66
67
68
23
42
43
44
45
46
65
66
67
68
46
65
66
67
68
69
88
89
90
91


In [5]:
n=10
# if n not in [8, 9]:
#     print('error')
# else:
#     print('OK')


if n == 8 or n==9:
    print('error')
else:
    print('OK')

OK


In [7]:
def  vector_rotation(vec,angle):
    theta = np.deg2rad(angle)
    rot = np.array([[math.cos(theta), -math.sin(theta)], [math.sin(theta), math.cos(theta)]])
    return np.dot(rot,vec)

a = np.array([-1,0])
b = vector_rotation(a,90)
b

array([-6.123234e-17, -1.000000e+00])

In [8]:
a=[1,2]
b=[3,4]
c=a+b
c

[1, 2, 3, 4]

In [5]:
a = -10
np.sign(a)

-1

In [3]:
math.pi

3.141592653589793